[package]
name = "redox-core"
version = "0.1.2"
edition = "2024"

[dependencies]
base64 = "0.22"
flate2 = "1.1"
anyhow = "1.0"
thiserror = "2.0"
glam = "0.30"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
